steps:
- task: Gradle5x@2
  inputs:
    gradleWrapperFile: 'other/gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    codeCoverageToolOption: 'JaCoCo'
    codeCoverageClassFilesDirectories: 'build/classes/java/main/'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './other/'
    ArtifactName: 'drop2'
    publishLocation: 'Container'
