steps:
- task: Gradle5x@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    codeCoverageToolOption: 'JaCoCo'
    codeCoverageClassFilesDirectories: 'project1/build/classes/java/main/,project2/build/classes/java/main/'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false