steps:
- task: Gradle5x@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    codeCoverageToolOption: 'JaCoCo'
    codeCoverageClassFilesDirectories: 'build/classes/java/main/,build/libs/'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'ls'
    workingDirectory: 'project1/build/classes/java/main/'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './'
    ArtifactName: 'drop2'
    publishLocation: 'Container'
